
# 自定义的配置
condition:
  name: A
  auto-prefix-api-package: com.example.shop.api
wx:
  appid: wx1b13619a00914149
  appsecret: d3f513878f1368a1aaed31d6482811a7
  code2session:  https://api.weixin.qq.com/sns/jscode2session?appid={0}&secret={1}&js_code={2}&grant_type=authorization_code
# 根据环境引入配置
spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true
server:
  port: 8081