condition:
  jwt-key: KokoTaSecret # 盐
  token-expired: 86400000 # 单位秒

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/seven_shop?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
