condition:
  jwt-key: KokoTaSecret # 盐
  token-expired: 604800 # 过期时间为 7 天
  max-sku-limit: 100 # 单品购买上限
  year-code: A,B,C,D,E,F,G,H,I,J,K,L # A 表示 2019 年

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/seven_shop?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
