condition:
  jwt-key: KokoTaSecret # 盐
  token-expired: 604800 # 过期时间为 7 天

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/seven_shop?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
